### Valid credentials
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "pwd123"
}

### Invalid credentials
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "invalid",
    "password": "*******"
}
